export const cardProperties = {
  "frost tree": {
    name: "frost tree",
    hp: 9,
    pts: 4,
    dmg: 2,
    type: "tree",
    rarity: "legendary",
  },
  "magical tree": {
    name: "magical tree",
    hp: 12,
    pts: 4,
    dmg: 2,
    type: "tree",
    rarity: "legendary",
  },
  oxytree: {
    name: "oxytree",
    hp: 9,
    pts: 3,
    dmg: 0,
    type: "tree",
    rarity: "legendary",
  },
  timberman: {
    name: "timberman",
    pts: 5,
    dmg: 15,
    type: "spell",
    intendedFor: "aimed",
    rarity: "legendary",
  },
  tornado: {
    name: "tornado",
    pts: 5,
    dmg: [6, 4, 2],
    type: "spell",
    intendedFor: "spread",
    rarity: "legendary",
  },
  acacia: {
    name: "acacia",
    hp: 3,
    pts: 5,
    dmg: 9,
    type: "tree",
    rarity: "rare",
  },
  baobab: {
    name: "baobab",
    hp: 17,
    pts: 9,
    dmg: 4,
    type: "tree",
    rarity: "rare",
  },
  chopper: {
    name: "chopper",
    hp: 9,
    pts: 6,
    dmg: 8,
    type: "bush",
    rarity: "rare",
  },
  "coconut palm": {
    name: "coconut palm",
    hp: 12,
    pts: 4,
    dmg: [20, 1],
    type: "tree",
    rarity: "rare",
  },
  corn: {
    name: "corn",
    hp: 9,
    pts: 5,
    dmg: 2,
    type: "bush",
    rarity: "rare",
  },
  creeper: {
    name: "creeper",
    hp: 6,
    pts: 3,
    dmg: 3,
    type: "bush",
    rarity: "rare",
  },
  freeze: {
    name: "freeze",
    pts: 3,
    dmg: 1,
    type: "spell",
    intendedFor: "aimed",
    rarity: "rare",
  },
  grove: {
    name: "grove",
    hp: 9,
    pts: 5,
    // dmg: 0,
    type: "building",
    rarity: "rare",
  },
  linden: {
    name: "linden",
    hp: 14,
    pts: 5,
    dmg: 2,
    type: "tree",
    rarity: "rare",
  },
  maple: {
    name: "maple",
    hp: 16,
    pts: 7,
    dmg: 2,
    type: "tree",
    rarity: "rare",
  },
  "medicinal herbs": {
    name: "medicinal herbs",
    hp: 5,
    pts: 3,
    type: "spell",
    intendedFor: "aimed",
    rarity: "rare",
  },
  "mining shaft": {
    name: "mining shaft",
    hp: 8,
    pts: 3,
    dmg: 1,
    type: "building",
    rarity: "rare",
  },
  rain: {
    // jeszcze o tym zatrzymywaniu pożaru i suszy dodać (potem) # todo
    name: "rain",
    hp: 3,
    pts: 4,
    type: "spell",
    intendedFor: "spread",
    rarity: "rare",
  },
  reed: {
    name: "reed",
    hp: 3,
    pts: 3,
    type: "bush",
    rarity: "rare",
  },
  "rubber tree": {
    name: "rubber tree",
    hp: 11,
    pts: 2,
    dmg: 3,
    type: "tree",
    rarity: "rare",
  },
  storm: {
    name: "storm",
    pts: 10,
    dmg: 9,
    type: "spell",
    intendedFor: "spread",
    rarity: "rare",
  },
  "apple tree": {
    name: "apple tree",
    hp: 7,
    pts: 3,
    dmg: 3,
    type: "tree",
    rarity: "common",
  },
  "bark beetles": {
    name: "bark beetles",
    pts: 3,
    dmg: 6,
    type: "spell",
    intendedFor: "aimed",
    rarity: "common",
  },
  birch: {
    name: "birch",
    hp: 12,
    pts: 4,
    dmg: 3,
    type: "tree",
    rarity: "common",
  },
  "bright tree": {
    name: "bright tree",
    hp: 14,
    pts: 4,
    dmg: 4,
    type: "tree",
    rarity: "common",
  },
  bush: {
    name: "bush",
    hp: 2,
    pts: 1,
    dmg: 1,
    type: "bush",
    rarity: "common",
  },
  chestnut: {
    name: "chestnut",
    hp: 6,
    pts: 4,
    dmg: 5,
    type: "tree",
    rarity: "common",
  },
  coffee: {
    name: "coffee",
    hp: 4,
    pts: 3,
    dmg: 2,
    type: "bush",
    rarity: "common",
  },
  conflagration: {
    name: "conflagration",
    pts: 3,
    dmg: [10, 6, 2, 0], // te wartości nie są nigdzie używane!! tylko do wgrywania karty w createCard
    type: "spell",
    intendedFor: "aimed",
    rarity: "common",
  },
  "dark moon": {
    name: "dark moon",
    pts: 5,
    dmg: 0,
    type: "spell",
    intendedFor: "spread",
    rarity: "common",
  },
  fir: {
    name: "fir",
    hp: 9,
    pts: 3,
    dmg: 1,
    type: "tree",
    rarity: "common",
  },
  "fire tree": {
    name: "fire tree",
    hp: 13,
    pts: 5,
    dmg: 1,
    type: "tree",
    rarity: "common",
  },
  fog: {
    name: "fog",
    pts: 4,
    dmg: 0, // 0.49 w % ale on nie ma!! on zmiejsza tylko
    type: "spell",
    intendedFor: "spread",
    rarity: "common",
  },
  hail: {
    name: "hail",
    pts: 1,
    dmg: 0,
    type: "spell",
    intendedFor: "aimed",
    rarity: "common",
  },
  locust: {
    name: "locust",
    pts: 4,
    dmg: [6, 1],
    type: "spell",
    intendedFor: "spread",
    rarity: "common",
  },
  meteorite: {
    name: "meteorite",
    pts: 4,
    dmg: 4,
    type: "spell",
    intendedFor: "aimed",
    rarity: "common",
  },
  naturalist: {
    name: "naturalist",
    pts: 2,
    dmg: 1,
    type: "spell",
    intendedFor: "aimed",
    rarity: "common",
  },
  pine: {
    name: "pine",
    hp: 9,
    pts: 3,
    dmg: 2,
    type: "tree",
    rarity: "common",
  },
  "poisonous tree": {
    name: "poisonous tree",
    hp: 4,
    pts: 3,
    dmg: 2,
    type: "tree",
    rarity: "common",
  },
  poplar: {
    name: "poplar",
    hp: 7,
    pts: 3,
    dmg: [4, 1],
    type: "tree",
    rarity: "common",
  },
  pumpkin: {
    name: "pumpkin",
    hp: 5,
    pts: 3,
    type: "bush",
    rarity: "common",
  },
  "red moon": {
    name: "red moon",
    pts: 6,
    dmg: 0,
    type: "spell",
    intendedFor: "spread",
    rarity: "common",
  },
  "royal tree": {
    name: "royal tree",
    hp: 15,
    pts: 8,
    dmg: 4,
    type: "tree",
    rarity: "common",
  },
  rust: {
    name: "rust",
    pts: 2,
    dmg: [8, 1],
    type: "spell",
    intendedFor: "aimed",
    rarity: "common",
  },
  snowstorm: {
    name: "snowstorm",
    pts: 4,
    dmg: 0,
    type: "spell",
    intendedFor: "spread",
    rarity: "common",
  },
  spruce: {
    name: "spruce",
    hp: 4,
    pts: 2,
    dmg: 2,
    type: "tree",
    rarity: "common",
  },
  "white wolf": {
    name: "white wolf",
    pts: 23,
    dmg: 25,
    type: "spell",
    intendedFor: "aimed",
    rarity: "common",
  },
  "wild berries": {
    name: "wild berries",
    hp: 3,
    pts: 3,
    dmg: 3,
    type: "bush",
    rarity: "common",
  },
  willow: {
    name: "willow",
    hp: 17,
    pts: 8,
    dmg: 5,
    type: "tree",
    rarity: "common",
  },
  yew: {
    name: "yew",
    hp: 5,
    pts: 3,
    dmg: [4, 1],
    type: "tree",
    rarity: "common",
  },
};