export const cardProperties = {
  timberman: {
    name: "timberman",
    pts: 5,
    dmg: 15,
    type: "spell",
    intendedFor: "aimed",
    rarity: "legendary",
  },
  acacia: {
    name: "acacia",
    hp: 3,
    pts: 5,
    dmg: 9,
    type: "tree",
    rarity: "rare",
  },
  chopper: {
    name: "chopper",
    hp: 9,
    pts: 6,
    dmg: 8,
    type: "bush",
    rarity: "rare",
  },
  creepers: {
    name: "creepers",
    hp: 6,
    pts: 3,
    dmg: 3,
    type: "bush",
    rarity: "rare",
  },
  linden: {
    name: "linden",
    hp: 14,
    pts: 5,
    dmg: 2,
    type: "tree",
    rarity: "rare",
  },
  "medicinal herbs": {
    name: "medicinal herbs",
    hp: 5,
    pts: 3,
    type: "spell",
    intendedFor: "aimed",
    rarity: "rare",
  },
  "apple tree": {
    name: "apple tree",
    hp: 7,
    pts: 3,
    dmg: 3,
    type: "tree",
    rarity: "common",
  },
  "bark beetles": {
    name: "bark beetles",
    pts: 3,
    dmg: 6,
    type: "spell",
    intendedFor: "aimed",
    rarity: "common",
  },
  birch: {
    name: "birch",
    hp: 12,
    pts: 4,
    dmg: 3,
    type: "tree",
    rarity: "common",
  },
  bush: {
    name: "bush",
    hp: 2,
    pts: 1,
    dmg: 1,
    type: "bush",
    rarity: "common",
  },
  chestnut: {
    name: "chestnut",
    hp: 6,
    pts: 4,
    dmg: 5,
    type: "tree",
    rarity: "common",
  },
  pine: {
    name: "pine",
    hp: 9,
    pts: 3,
    dmg: 2,
    type: "tree",
    rarity: "common",
  },
  poplar: {
    name: "poplar",
    hp: 7,
    pts: 3,
    dmg: [4, 1],
    type: "tree",
    rarity: "common",
  },
  spruce: {
    name: "spruce",
    hp: 4,
    pts: 2,
    dmg: 2,
    type: "tree",
    rarity: "common",
  },
  willow: {
    name: "willow",
    hp: 17,
    pts: 8,
    dmg: 5,
    type: "tree",
    rarity: "common",
  },
};